### ISSUE TITLE
OnRowSelect rerender all components in table

### ISSUE THREAD

**Issue by PatrykFij** [TanStack/table#4092]
### Describe the bug

Hi, 
I have problem with row selecting. Every time when I click on new row all components in the table rerender. Probably it looks like problem with using useFormContext from react-hook-form. Is this possible to optimize this behaviour and not refresh all component if it is not needed?

### Your minimal, reproducible example

https://codesandbox.io/s/virtualized-form-table-using-react-table-react-window-react-hook-form-gyyym3

### Steps to reproduce

1. Open this example in separate window and set as enable "Highlight updates when components render." in you profiler extention.

2.  Click on any row. Selected row should have red background but with delay. All components rerender.

### Expected behavior

Click on row shouldn't refresh all components in the table and row should be highlighted immediately

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/62008203/177133155-ec5d81c7-7d4f-47ef-9132-456e022684db.png)

### Platform

Chrome

### react-table version

17.0.1

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
This is just React doing what it's supposed to do. The state for the table lives in the `useReactTable` hook, so when you update a row selection, the component that houses your table hook instance will rerender, including rerendering any and all child components. Here's my suggestions:

1. Generally, you want this. This is what keeps your UI in sync with your state.
2. Consider rendering fewer rows. 100 rows * 10 columns is at least 1000 component instances. Paginate or virtualize your rows if necessary.
3. Instead of *avoiding* rerenders, make them faster. If your table components or cell/header templates are slow, your table will also be slow. Memoize where necessary
4. As a last resort, you can use `React.Memo` or `useMemo` to memoize your actual components or their output, but this means that they will **only rerender when their dependencies change**. Unless you know what you're doing here, you'll likely run into more problems with out-of-sync UI doing this.
