### ISSUE TITLE
React table's state not working correctly when used in a React context

### ISSUE THREAD

**Issue by carlesba** [TanStack/table#4681]
### Describe the bug

1. Create a table
2. Pass the table's value to a provider
3. consume table's value through a context
4. try to resize the table

Table is not resizing

This works when the context is eliminated and the value is used directly in the component. 

### Your minimal, reproducible example

https://codesandbox.io/s/adoring-brook-h54om7?file=/src/App.tsx

### Steps to reproduce

1. Resize columns to check it works as expected
2. click on the `toggle` button to switch to a context state
3. resize columns again. nothing happens

### Expected behavior

Table should work fine even when used in a context

### How often does this bug happen?

Every time

### Platform

Chrome

### react-table version

8.7.8

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by carlesba** [comment]
This issue seems to explain the reason https://github.com/TanStack/table/issues/2344

The table's instance keeps the same reference so the context won't update. Wrapping that reference into an object generates a new instance on every change.

IMO, this seems very counterintuitive in react's ecosystem and should be changed (or at least documented somewhere). It doesn't play nice with other state management in React's ecosystem.

**Comment by jonahallibone** [comment]
I've also had trouble with this, where memoization will actually break `getIsSelected()` and other such behaviors. It's incredibly frustrating because I've seen advocation for "optimizing for rerenders" but providing no examples for how to do that. This behavior breaks the rest of Reacts memoization out of the box, so some examples of how they expect us to do this would be great. I've observed `ag-grid` behaving well in regards to rerenders, so I know it is possible. It would be great to get an example of how to replicate this behavior without needing to pay $999 for a license.
