### ISSUE TITLE
Columns no longer resizable when table overflow occurs 

### ISSUE THREAD

**Issue by marizf888** [TanStack/table#5388]
### TanStack Table version

v8.11.3

### Framework/Library version

React v18

### Describe the bug and the steps to reproduce it

1) Add more columns to a table (with column resizing enabled) until overflow occurs
2) Try to resize a table column. You will notice it is no longer possible

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

N/A

### Screenshots or Videos (Optional)

[Screen Recording 2024-03-04 at 9.36.30 AM.zip](https://github.com/TanStack/table/files/14485175/Screen.Recording.2024-03-04.at.9.36.30.AM.zip)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by danverbs** [comment]
I had this issue and added minWidth to the th element but that now pushes the table beyond the width of it's parent, even though overflow-auto is on

Does this happen for you too if you try adding it?

**Comment by KevinVandy** [comment]
no sandobox or code that you shared, but guessing you just don't have `overflow: 'auto'` on the table container element.

**Comment by jesterhuizen** [comment]
I have the same issue. 

My table has many columns, which can be added as the user requires. Some have minimal data (think individual numbers) and others have large amounts of data (think large text comments over multiple paragraphs).

My intended usecase is that the user can resize data heavy columns to ease reading and fit multiple rows on the screen, then just needing to scroll horizontally.

I have created a minimal fork of the example code [here](https://stackblitz.com/edit/tanstack-table-lfbzxzpz?file=src%2Fmain.tsx&preset=node)

As shown in the example, when the table container is constrained so that all columns are at minimum width, increasing a columns individual width is no longer possible.

My assumption is that the column resize adjusts ratios between columns, and does not simply increase column size, thus being constrained by the max-width of the table. Is this correct?

I would like a solution or some guidance here, as the experience of a ton of vertical scrolling is not ideal.
